extension_dir = "C:\Users\Tenzin Lodoe\Downloads\Sakhang-Database\ext"
extension=mbstring
extension=openssl
extension=pdo_mysql
extension=pdo_sqlite
extension=sqlite3
extension=fileinfo
extension=curl
extension=pdo_pgsql
extension=pgsql
extension=gd
