<?php

return [
    'buildings' => [
        'Staff Quarter near Sherig Lekhung',
        'Yidhe Khang (Lhagyari Leshak)',
        'Sonam Khang',
        'Kelsang Khang',
        'Kashag Guest House(Behind Health Dept)',
        'Delek & Dickyi Khang',
        'Songtsen Khang',
        'Nelaykhang Leshak',
        'Dickey Khang',
        'Moenkyi Khang',
        'Rabten Khang',
        'Nangsi Leshak',
        'Desung Leshak',
        'Namsay Khang',
        'Phuntsok Khang',
        'Shering Nyiho Khang (Sunny Hostel)',
        'Shugseb Gatseling',
        'Namgyal Khang',
        'Shedey Khang',
        'Lekmon Khang',
        'Thogmoen Khang',
        'Pelbar Khang',
        'Phelgye Khang',
        'Shiney Khang',
        'Ganden Khang (Chitue)',
        'Phendhe Khang',
        'Gangchen Khangsar (Kolon)',
        'Tashi Khangsar',
    ],
    'rooms' => range(1, 40),
];
